atk_bg = {
    "explosive": "#920108",
    "piercing": "#BE8905",
    "mystic": "#236D9A",
    "sonic": "#9745A7"
}

def_bg = {
    "light": "#920108",
    "heavy": "#BE8905",
    "special": "#236D9A",
    "elastic": "#9745A7"
}

student_data = {
    1157: {
        "name": "Ichika",
        "school": "Trinity",
        "bg": "trinity",
        "type": "striker",
        "role": "dealer",
        "position": "middle",
        "atk_type": "sonic",
        "def_type": "heavy",
        "mood1": "outstanding",
        "mood2": "neutral",
        "mood3": "terrible",
        "ex": "fan",
        "basic": "bullet-buff",
        "enhanced": "weapon-buff",
        "sub": "extra-dmg",
        "cover": True,
        "weapon_type": "ar",
        "weapon_img": 1157,
        "weapon_name": "Red Dragon",
        "gear1": "hat",
        "gear2": "hairpin",
        "gear3": "watch"
    },
    1127: {
        "name": "Mika",
        "school": "Trinity",
        "bg": "trinity",
        "type": "striker",
        "role": "dealer",
        "position": "front",
        "atk_type": "piercing",
        "def_type": "light",
        "mood1": "terrible",
        "mood2": "good",
        "mood3": "outstanding",
        "ex": "target",
        "basic": "target",
        "enhanced": "weapon-buff",
        "sub": "mika-sub",
        "cover": True,
        "weapon_type": "smg",
        "weapon_img": 1127,
        "weapon_name": "Quis ut Deus",
        "gear1": "hat",
        "gear2": "badge",
        "gear3": "watch"
    },
    1020: {
        "name": "Iori",
        "school": "Gehenna",
        "bg": "gehenna",
        "type": "striker",
        "role": "dealer",
        "position": "back",
        "atk_type": "piercing",
        "def_type": "heavy",
        "mood1": "bad",
        "mood2": "bad",
        "mood3": "outstanding",
        "ex": "fan",
        "basic": "target",
        "enhanced": "weapon-buff",
        "sub": "extra-dmg",
        "cover": True,
        "weapon_type": "sr",
        "weapon_img": 1020,
        "weapon_name": "Crack Shot",
        "gear1": "hat",
        "gear2": "hairpin",
        "gear3": "watch"
    },
    1108: {
        "name": "Saori",
        "school": "Arius",
        "bg": "arius",
        "type": "striker",
        "role": "dealer",
        "position": "middle",
        "atk_type": "explosive",
        "def_type": "special",
        "mood1": "neutral",
        "mood2": "terrible",
        "mood3": "outstanding",
        "ex": "always-crit",
        "basic": "always-crit",
        "enhanced": "weapon-buff",
        "sub": "weapon-buff",
        "cover": True,
        "weapon_type": "ar",
        "weapon_img": 1108,
        "weapon_name": "Arius Assault Rifle",
        "gear1": "hat",
        "gear2": "hairpin",
        "gear3": "watch"
    },
    1058: {
        "name": "Azusa (Swimsuit)",
        "school": "Trinity",
        "bg": "beach",
        "type": "striker",
        "role": "dealer",
        "position": "middle",
        "atk_type": "mystic",
        "def_type": "light",
        "mood1": "bad",
        "mood2": "bad",
        "mood3": "outstanding",
        "ex": "chill",
        "basic": "weapon-buff",
        "enhanced": "weapon-buff",
        "sub": "stat-debuff",
        "cover": True,
        "weapon_type": "ar",
        "weapon_img": 1055,
        "weapon_name": "Et Omnia Vanitas",
        "gear1": "gloves",
        "gear2": "hairpin",
        "gear3": "watch"
    },
    1109: {
        "name": "Kazusa",
        "school": "Trinity",
        "bg": "trinity",
        "type": "striker",
        "role": "dealer",
        "position": "back",
        "atk_type": "piercing",
        "def_type": "heavy",
        "mood1": "outstanding",
        "mood2": "terrible",
        "mood3": "neutral",
        "ex": "target",
        "basic": "weapon-buff",
        "enhanced": "weapon-buff",
        "sub": "weapon-dual-effect",
        "cover": False,
        "weapon_type": "mg",
        "weapon_img": 1109,
        "weapon_name": "Mabinogion",
        "gear1": "gloves",
        "gear2": "hairpin",
        "gear3": "watch"
    },
}