data = {
    1157: {
        "name": "Ichika",
        "school": "Trinity",
        "bg": "trinity",
        "type": "striker",
        "role": "dealer",
        "position": "middle",
        "atk_type": "sonic",
        "def_type": "heavy",
        "mood1": "outstanding",
        "mood2": "neutral",
        "mood3": "terrible",
        "ex": "fan",
        "basic": "bullet-buff",
        "enhanced": "weapon-buff",
        "sub": "extra-dmg",
        "cover": True,
        "weapon_type": "ar",
        "weapon_name": "Red Dragon",
        "gear1": "hat",
        "gear2": "hairpin",
        "gear3": "watch"
    },
    1127: {
        "name": "Mika",
        "school": "Trinity",
        "bg": "trinity",
        "type": "striker",
        "role": "dealer",
        "position": "front",
        "atk_type": "piercing",
        "def_type": "light",
        "mood1": "terrible",
        "mood2": "good",
        "mood3": "outstanding",
        "ex": "target",
        "basic": "target",
        "enhanced": "weapon-buff",
        "sub": "mika-sub",
        "cover": True,
        "weapon_type": "smg",
        "weapon_name": "Quis ut Deus",
        "gear1": "hat",
        "gear2": "badge",
        "gear3": "watch"
    },
    1020: {
        "name": "Iori",
        "school": "Gehenna",
        "bg": "gehenna",
        "type": "striker",
        "role": "dealer",
        "position": "back",
        "atk_type": "piercing",
        "def_type": "heavy",
        "mood1": "bad",
        "mood2": "bad",
        "mood3": "outstanding",
        "ex": "fan",
        "basic": "target",
        "enhanced": "weapon-buff",
        "sub": "extra-dmg",
        "cover": True,
        "weapon_type": "sr",
        "weapon_name": "Crack Shot",
        "gear1": "hat",
        "gear2": "hairpin",
        "gear3": "watch"
    },
    1108: {
        "name": "Saori",
        "school": "Arius",
        "bg": "arius",
        "type": "striker",
        "role": "dealer",
        "position": "middle",
        "atk_type": "explosive",
        "def_type": "light",
        "mood1": "neutral",
        "mood2": "terrible",
        "mood3": "outstanding",
        "ex": "always-crit",
        "basic": "always-crit",
        "enhanced": "weapon-buff",
        "sub": "weapon-buff",
        "cover": True,
        "weapon_type": "ar",
        "weapon_name": "Arius Assault Rifle",
        "gear1": "hat",
        "gear2": "hairpin",
        "gear3": "watch"
    },
    1058: {
        "name": "Azusa (Swimsuit)",
        "school": "Trinity",
        "bg": "beach",
        "type": "striker",
        "role": "dealer",
        "position": "middle",
        "atk_type": "mystic",
        "def_type": "light",
        "mood1": "bad",
        "mood2": "bad",
        "mood3": "outstanding",
        "ex": "chill",
        "basic": "weapon-buff",
        "enhanced": "weapon-buff",
        "sub": "stat-debuff",
        "cover": True,
        "weapon_type": "ar",
        "weapon_name": "Et Omnia Vanitas",
        "gear1": "gloves",
        "gear2": "hairpin",
        "gear3": "watch"
    },
    1109: {
        "name": "Kazusa",
        "school": "Trinity",
        "bg": "trinity",
        "type": "striker",
        "role": "dealer",
        "position": "back",
        "atk_type": "piercing",
        "def_type": "heavy",
        "mood1": "outstanding",
        "mood2": "terrible",
        "mood3": "neutral",
        "ex": "target",
        "basic": "weapon-buff",
        "enhanced": "weapon-buff",
        "sub": "weapon-dual-effect",
        "cover": False,
        "weapon_type": "mg",
        "weapon_name": "Mabinogion",
        "gear1": "gloves",
        "gear2": "hairpin",
        "gear3": "watch"
    }
}